//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloatynosyNue.Locales {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloatynosyNue.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable File Explorer Ads ähnelt.
        /// </summary>
        internal static string _adsFileExplorerAds {
            get {
                return ResourceManager.GetString("_adsFileExplorerAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in File Explorer. ähnelt.
        /// </summary>
        internal static string _adsFileExplorerAds_desc {
            get {
                return ResourceManager.GetString("_adsFileExplorerAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Finish Setup Ads ähnelt.
        /// </summary>
        internal static string _adsFinishSetupAds {
            get {
                return ResourceManager.GetString("_adsFinishSetupAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable the &quot;Lets finish setting up your device&quot; and other advertising. ähnelt.
        /// </summary>
        internal static string _adsFinishSetupAds_desc {
            get {
                return ResourceManager.GetString("_adsFinishSetupAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Lock Screen Tips and Ads ähnelt.
        /// </summary>
        internal static string _adsLockScreenAds {
            get {
                return ResourceManager.GetString("_adsLockScreenAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable tips and ads on the lock screen. ähnelt.
        /// </summary>
        internal static string _adsLockScreenAds_desc {
            get {
                return ResourceManager.GetString("_adsLockScreenAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Personalized Ads ähnelt.
        /// </summary>
        internal static string _adsPersonalizedAds {
            get {
                return ResourceManager.GetString("_adsPersonalizedAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable personalized ads. ähnelt.
        /// </summary>
        internal static string _adsPersonalizedAds_desc {
            get {
                return ResourceManager.GetString("_adsPersonalizedAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Settings Ads ähnelt.
        /// </summary>
        internal static string _adsSettingsAds {
            get {
                return ResourceManager.GetString("_adsSettingsAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in settings. ähnelt.
        /// </summary>
        internal static string _adsSettingsAds_desc {
            get {
                return ResourceManager.GetString("_adsSettingsAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Start menu Ads ähnelt.
        /// </summary>
        internal static string _adsStartmenuAds {
            get {
                return ResourceManager.GetString("_adsStartmenuAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in the start menu. ähnelt.
        /// </summary>
        internal static string _adsStartmenuAds_desc {
            get {
                return ResourceManager.GetString("_adsStartmenuAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Tailored experiences ähnelt.
        /// </summary>
        internal static string _adsTailoredExperiences {
            get {
                return ResourceManager.GetString("_adsTailoredExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tailored Experiences allows Microsoft to get information from you to deliver personalized tips, ads, and recommendations. Many people would call this telemetry, or even spying. ähnelt.
        /// </summary>
        internal static string _adsTailoredExperiences_desc {
            get {
                return ResourceManager.GetString("_adsTailoredExperiences_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable General Tips and Ads ähnelt.
        /// </summary>
        internal static string _adsTipsAndSuggestions {
            get {
                return ResourceManager.GetString("_adsTipsAndSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable general tips and ads. ähnelt.
        /// </summary>
        internal static string _adsTipsAndSuggestions_desc {
            get {
                return ResourceManager.GetString("_adsTipsAndSuggestions_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Welcome Experience Ads ähnelt.
        /// </summary>
        internal static string _adsWelcomeExperienceAds {
            get {
                return ResourceManager.GetString("_adsWelcomeExperienceAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable ads in the welcome experience. ähnelt.
        /// </summary>
        internal static string _adsWelcomeExperienceAds_desc {
            get {
                return ResourceManager.GetString("_adsWelcomeExperienceAds_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Show Copilot in Taskbar ähnelt.
        /// </summary>
        internal static string _aiCopilotTaskbar {
            get {
                return ResourceManager.GetString("_aiCopilotTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Copilot in Taskbar. ähnelt.
        /// </summary>
        internal static string _aiCopilotTaskbar_desc {
            get {
                return ResourceManager.GetString("_aiCopilotTaskbar_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Allow system-wide snapshots ähnelt.
        /// </summary>
        internal static string _aiRecallMachine {
            get {
                return ResourceManager.GetString("_aiRecallMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable system-wide snapshots. ähnelt.
        /// </summary>
        internal static string _aiRecallMachine_desc {
            get {
                return ResourceManager.GetString("_aiRecallMachine_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Allow Windows to save snapshots of your screen ähnelt.
        /// </summary>
        internal static string _aiRecallUser {
            get {
                return ResourceManager.GetString("_aiRecallUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Recall from saving snapshots of your screen.&quot; ähnelt.
        /// </summary>
        internal static string _aiRecallUser_desc {
            get {
                return ResourceManager.GetString("_aiRecallUser_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Game DVR ähnelt.
        /// </summary>
        internal static string _gamingGameDVR {
            get {
                return ResourceManager.GetString("_gamingGameDVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Game DVR. ähnelt.
        /// </summary>
        internal static string _gamingGameDVR_desc {
            get {
                return ResourceManager.GetString("_gamingGameDVR_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Power Throttling ähnelt.
        /// </summary>
        internal static string _gamingPowerThrottling {
            get {
                return ResourceManager.GetString("_gamingPowerThrottling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Power Throttling. ähnelt.
        /// </summary>
        internal static string _gamingPowerThrottling_desc {
            get {
                return ResourceManager.GetString("_gamingPowerThrottling_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Visual Effects ähnelt.
        /// </summary>
        internal static string _gamingVisualFX {
            get {
                return ResourceManager.GetString("_gamingVisualFX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable visual effects in Windows. ähnelt.
        /// </summary>
        internal static string _gamingVisualFX_desc {
            get {
                return ResourceManager.GetString("_gamingVisualFX_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable activity history ähnelt.
        /// </summary>
        internal static string _privacyActivityHistory {
            get {
                return ResourceManager.GetString("_privacyActivityHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable activity history (prevents Windows from tracking and storing your activity) ähnelt.
        /// </summary>
        internal static string _privacyActivityHistory_desc {
            get {
                return ResourceManager.GetString("_privacyActivityHistory_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable location tracking ähnelt.
        /// </summary>
        internal static string _privacyLocationTracking {
            get {
                return ResourceManager.GetString("_privacyLocationTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable location tracking (prevents Windows from accessing your location) ähnelt.
        /// </summary>
        internal static string _privacyLocationTracking_desc {
            get {
                return ResourceManager.GetString("_privacyLocationTracking_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Privacy Settings Experience at sign-in ähnelt.
        /// </summary>
        internal static string _privacyPrivacyExperience {
            get {
                return ResourceManager.GetString("_privacyPrivacyExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable Privacy Settings Experience at sign-in. ähnelt.
        /// </summary>
        internal static string _privacyPrivacyExperience_desc {
            get {
                return ResourceManager.GetString("_privacyPrivacyExperience_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turn off Telemetry data collection ähnelt.
        /// </summary>
        internal static string _privacyTelemetry {
            get {
                return ResourceManager.GetString("_privacyTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will turn off telemetry data collection and prevent the data from being sent to Microsoft. ähnelt.
        /// </summary>
        internal static string _privacyTelemetry_desc {
            get {
                return ResourceManager.GetString("_privacyTelemetry_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Full context menus in Windows 11 ähnelt.
        /// </summary>
        internal static string _uiFullContextMenus {
            get {
                return ResourceManager.GetString("_uiFullContextMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will enable full context menus in Windows 11. ähnelt.
        /// </summary>
        internal static string _uiFullContextMenus_desc {
            get {
                return ResourceManager.GetString("_uiFullContextMenus_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t use personalized lock screen ähnelt.
        /// </summary>
        internal static string _uiLockScreen {
            get {
                return ResourceManager.GetString("_uiLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will disable the personalized lock screen. ähnelt.
        /// </summary>
        internal static string _uiLockScreen_desc {
            get {
                return ResourceManager.GetString("_uiLockScreen_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide search box on taskbar ähnelt.
        /// </summary>
        internal static string _uiSearchboxTaskbarMode {
            get {
                return ResourceManager.GetString("_uiSearchboxTaskbarMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will hide search box on taskbar ähnelt.
        /// </summary>
        internal static string _uiSearchboxTaskbarMode_desc {
            get {
                return ResourceManager.GetString("_uiSearchboxTaskbarMode_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Most used apps in start menu ähnelt.
        /// </summary>
        internal static string _uiShowOrHideMostUsedApps {
            get {
                return ResourceManager.GetString("_uiShowOrHideMostUsedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will hide Most used apps in start menu ähnelt.
        /// </summary>
        internal static string _uiShowOrHideMostUsedApps_desc {
            get {
                return ResourceManager.GetString("_uiShowOrHideMostUsedApps_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Task view button on taskbar ähnelt.
        /// </summary>
        internal static string _uiShowTaskViewButton {
            get {
                return ResourceManager.GetString("_uiShowTaskViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will hide the Task view button on taskbar ähnelt.
        /// </summary>
        internal static string _uiShowTaskViewButton_desc {
            get {
                return ResourceManager.GetString("_uiShowTaskViewButton_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pin more Apps on start menu ähnelt.
        /// </summary>
        internal static string _uiStartLayout {
            get {
                return ResourceManager.GetString("_uiStartLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will allow pinning more Apps on start menu ähnelt.
        /// </summary>
        internal static string _uiStartLayout_desc {
            get {
                return ResourceManager.GetString("_uiStartLayout_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Start button to left ähnelt.
        /// </summary>
        internal static string _uiTaskbarAlignment {
            get {
                return ResourceManager.GetString("_uiTaskbarAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature will align the Start button to left ähnelt.
        /// </summary>
        internal static string _uiTaskbarAlignment_desc {
            get {
                return ResourceManager.GetString("_uiTaskbarAlignment_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        internal static string ctl_btnBack {
            get {
                return ResourceManager.GetString("ctl_btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dumputer™ ähnelt.
        /// </summary>
        internal static string ctl_btnDumputer {
            get {
                return ResourceManager.GetString("ctl_btnDumputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Experience ähnelt.
        /// </summary>
        internal static string ctl_btnExperience {
            get {
                return ResourceManager.GetString("ctl_btnExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Donate ähnelt.
        /// </summary>
        internal static string ctl_Donate {
            get {
                return ResourceManager.GetString("ctl_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to donate? ähnelt.
        /// </summary>
        internal static string ctl_DonateAsk {
            get {
                return ResourceManager.GetString("ctl_DonateAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enjoying Bloatynosy Nue? If you’d like to support the project, any donation helps keep things going. Thanks a ton!;
        ///If Bloatynosy Nue made your day easier, consider dropping a small donation to keep the magic alive! Every little bit helps!;
        ///Like what Bloatynosy Nue does? Throw a small donation my way and help make it even better! Thanks in advance! 😄;
        ///If you&apos;re enjoying Windows 11 thanks to Bloatynosy Nue, a donation would be awesome to keep the project alive. Much appreciated!;
        ///Loving the results from [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ctl_DonationPrompts {
            get {
                return ResourceManager.GetString("ctl_DonationPrompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set up Windows 11 ähnelt.
        /// </summary>
        internal static string ctl_lblHeader {
            get {
                return ResourceManager.GetString("ctl_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I would like to ähnelt.
        /// </summary>
        internal static string ctl_lblSteps {
            get {
                return ResourceManager.GetString("ctl_lblSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level up Windows 11 privacy and personalization, declutter by removing bloatware, and supercharge functionality with community plugins. ähnelt.
        /// </summary>
        internal static string ctl_lblSubHeader {
            get {
                return ResourceManager.GetString("ctl_lblSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string formDumputer_ctl_btnUninstall {
            get {
                return ResourceManager.GetString("formDumputer_ctl_btnUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details about selected app ähnelt.
        /// </summary>
        internal static string formDumputer_ctl_lblDetails {
            get {
                return ResourceManager.GetString("formDumputer_ctl_lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application Dump ähnelt.
        /// </summary>
        internal static string formDumputer_ctl_lblHeader {
            get {
                return ResourceManager.GetString("formDumputer_ctl_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ähnelt.
        /// </summary>
        internal static string formDumputer_ctl_lblSort {
            get {
                return ResourceManager.GetString("formDumputer_ctl_lblSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move apps from the left basket to the right trash can to delete them ähnelt.
        /// </summary>
        internal static string formDumputer_ctl_lblSubHeader {
            get {
                return ResourceManager.GetString("formDumputer_ctl_lblSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string formDumputer_ctl_textBoxSearch {
            get {
                return ResourceManager.GetString("formDumputer_ctl_textBoxSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App packages loaded: ähnelt.
        /// </summary>
        internal static string formDumputer_status_countPackages {
            get {
                return ResourceManager.GetString("formDumputer_status_countPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error removing ähnelt.
        /// </summary>
        internal static string formDumputer_status_failedRemove {
            get {
                return ResourceManager.GetString("formDumputer_status_failedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading appx packages... ähnelt.
        /// </summary>
        internal static string formDumputer_status_Loading {
            get {
                return ResourceManager.GetString("formDumputer_status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No items in the trash yet ähnelt.
        /// </summary>
        internal static string formDumputer_status_noItems {
            get {
                return ResourceManager.GetString("formDumputer_status_noItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refreshing app list... ähnelt.
        /// </summary>
        internal static string formDumputer_status_Refreshing {
            get {
                return ResourceManager.GetString("formDumputer_status_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attempting to remove ähnelt.
        /// </summary>
        internal static string formDumputer_status_Removing {
            get {
                return ResourceManager.GetString("formDumputer_status_Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully removed ähnelt.
        /// </summary>
        internal static string formDumputer_status_successRemove {
            get {
                return ResourceManager.GetString("formDumputer_status_successRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        internal static string formDumputer_tt_btnAdd {
            get {
                return ResourceManager.GetString("formDumputer_tt_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        internal static string formDumputer_tt_btnRefresh {
            get {
                return ResourceManager.GetString("formDumputer_tt_btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        internal static string formDumputer_tt_btnRemove {
            get {
                return ResourceManager.GetString("formDumputer_tt_btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept and apply ähnelt.
        /// </summary>
        internal static string formExperience_ctl_btnApply {
            get {
                return ResourceManager.GetString("formExperience_ctl_btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decline ähnelt.
        /// </summary>
        internal static string formExperience_ctl_btnRevert {
            get {
                return ResourceManager.GetString("formExperience_ctl_btnRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize Experience ähnelt.
        /// </summary>
        internal static string formExperience_ctl_lblHeader {
            get {
                return ResourceManager.GetString("formExperience_ctl_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ähnelt.
        /// </summary>
        internal static string formExperience_ctl_lblSort {
            get {
                return ResourceManager.GetString("formExperience_ctl_lblSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click &quot;Accept and Apply&quot; to proceed, or &quot;Decline&quot; to keep the default settings. Individual adjustments can also be made. ähnelt.
        /// </summary>
        internal static string formExperience_ctl_lblSubHeader {
            get {
                return ResourceManager.GetString("formExperience_ctl_lblSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string formExperience_ctl_textBoxSearch {
            get {
                return ResourceManager.GetString("formExperience_ctl_textBoxSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accepted ähnelt.
        /// </summary>
        internal static string formExperience_status_Accepted {
            get {
                return ResourceManager.GetString("formExperience_status_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Declined ähnelt.
        /// </summary>
        internal static string formExperience_status_Declined {
            get {
                return ResourceManager.GetString("formExperience_status_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        internal static string formExperience_status_Disabled {
            get {
                return ResourceManager.GetString("formExperience_status_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        internal static string formExperience_status_Enabled {
            get {
                return ResourceManager.GetString("formExperience_status_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to update feature status due to insufficient permissions. ähnelt.
        /// </summary>
        internal static string formExperience_statusPermissions {
            get {
                return ResourceManager.GetString("formExperience_statusPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string formPlugins_ctl_btnNext {
            get {
                return ResourceManager.GetString("formPlugins_ctl_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visit Store ähnelt.
        /// </summary>
        internal static string formPlugins_ctl_btnPluginStore {
            get {
                return ResourceManager.GetString("formPlugins_ctl_btnPluginStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extensions ähnelt.
        /// </summary>
        internal static string formPlugins_ctl_lblHeader {
            get {
                return ResourceManager.GetString("formPlugins_ctl_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed ähnelt.
        /// </summary>
        internal static string formPlugins_ctl_lblInstalled {
            get {
                return ResourceManager.GetString("formPlugins_ctl_lblInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More Possibilities with Bloatynosy Nue 
        ///Plugins ähnelt.
        /// </summary>
        internal static string formPlugins_ctl_lblSubHeader {
            get {
                return ResourceManager.GetString("formPlugins_ctl_lblSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The plugin environment is not ready.\n\nWould you like to enable the store and download the required components? ähnelt.
        /// </summary>
        internal static string formPlugins_status_notReady {
            get {
                return ResourceManager.GetString("formPlugins_status_notReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete! \nThe Store is ready to use. ähnelt.
        /// </summary>
        internal static string formPlugins_status_Ready {
            get {
                return ResourceManager.GetString("formPlugins_status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        internal static string formPluginsReview_ctl_btnRun {
            get {
                return ResourceManager.GetString("formPluginsReview_ctl_btnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View script ähnelt.
        /// </summary>
        internal static string formPluginsReview_ctl_btnViewSc {
            get {
                return ResourceManager.GetString("formPluginsReview_ctl_btnViewSc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Review your selections ähnelt.
        /// </summary>
        internal static string formPluginsReview_ctl_lblHeader {
            get {
                return ResourceManager.GetString("formPluginsReview_ctl_lblHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No plugins selected. Please select plugins to apply or revert. ähnelt.
        /// </summary>
        internal static string formPluginsReview_status_Summary {
            get {
                return ResourceManager.GetString("formPluginsReview_status_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To be applied ähnelt.
        /// </summary>
        internal static string formPluginsReview_status_tobeApplied {
            get {
                return ResourceManager.GetString("formPluginsReview_status_tobeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To be Reverted ähnelt.
        /// </summary>
        internal static string formPluginsReview_status_tobeReverted {
            get {
                return ResourceManager.GetString("formPluginsReview_status_tobeReverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About this app ähnelt.
        /// </summary>
        internal static string tt_btnAboutApp {
            get {
                return ResourceManager.GetString("tt_btnAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove pre-installed apps on Windows 11 (24H2 and 23H2) to declutter your system ähnelt.
        /// </summary>
        internal static string tt_btnDumputer {
            get {
                return ResourceManager.GetString("tt_btnDumputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize Windows 11 settings for enhanced privacy, control, and personalization ähnelt.
        /// </summary>
        internal static string tt_btnExperience {
            get {
                return ResourceManager.GetString("tt_btnExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        internal static string tt_btnLogger {
            get {
                return ResourceManager.GetString("tt_btnLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string tt_btnPlugins {
            get {
                return ResourceManager.GetString("tt_btnPlugins", resourceCulture);
            }
        }
    }
}
